### ISSUE TITLE
Text Files (wildcards) not being called up properly

### ISSUE THREAD

**Issue by agoncam20** [ltdrdata/ComfyUI-Impact-Pack#1136]
when attempting to run wildcards the txt files on the wildcards folder are not being called via __text__

however written wildcards in the standard format of { test1 | test2} are, any idea what the issue might be? I have tried placing the file in either folder too

![Image](https://github.com/user-attachments/assets/991eb3f1-0c81-4ec4-82ef-fb41bea1d72b)

**Comment by aiworkforall** [comment]
<img width="760" height="616" alt="Image" src="https://github.com/user-attachments/assets/7e3a2a57-e0cd-43a9-8a4e-8e455905609f" />

"I also struggled with this issue for a long time, but it was resolved after I clicked this button."

path : comfyui-impact-pack\wildcards

**Comment by agoncam20** [comment]
HUH!? I DONT HAVE THAT OPTION LMAO

**Comment by agoncam20** [comment]
I tried updating wildcards via the edit function and nothing unfortunately

**Comment by ltdrdata** [comment]
> HUH!? I DONT HAVE THAT OPTION LMAO

Make sure your Impact Pack and ComfyUI is up to date.

**Comment by darkvsword** [comment]
After the update, I encountered the same issue, but it is still not resolved. Is there any other possible solution or place that needs further checking?
