### ISSUE TITLE
Control RegionalSampler Noise

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#198]
This is working pretty well, but often the image is totally different, like the mask is ignored.  Is there a way to control the noise outside of the masked area as this really altering the image in a big way in 60% of the time.

On a side note, I would also love it if you had more hints as to what a lot of these settings mean, as they are not documented anywhere. I wish these nodes would show the comment code so we could figure out the different between "dilation" and "threshold" for example in the "SAM Detector."

**Comment by ltdrdata** [comment]
The Regional Sampler is a node that I've been experimenting with in various ways. 

One distinctive feature of the Regional Sampler is that it performs denoising together for each region at every step. When conventional inpainting a mask area, the outside of the mask is fixed so that it no longer changes. However, in the case of Regional Sampling, both the mask area and the outside area interact with each other during the sampling process.

Even if it doesn't directly denoise beyond its own region when denoising a specific region, each region adjusts itself while taking into account the image state beyond its region.

The part defined by the `overlap_factor` is the unique area where the regions overlap between the borders, and it's the only part where each region collaboratively denoises.

Additionally, although I haven't uploaded a tutorial yet, I've added two nodes to the `Inspire Pack` to complement the Regional Sampler.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-sampling.png

**Comment by sedetweiler** [comment]
Great!  I am working with it now.  Still having issues getting the SEGM to find the face, as the body model is obvious.

**Comment by sedetweiler** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/f41694fa-7366-4078-a029-e4b8b64819c1)
Not sure how to get SEGM to give me the face here for replacement, since I don't want to paste a mask on each image as they are inferenced.

**Comment by sedetweiler** [comment]
This is what I was doing, and this seems like a long trip, but perhaps this is the best way.  
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/b8c9b89c-ebdd-4a61-ab7c-1874cfc9eaf9)

**Comment by ltdrdata** [comment]
> Not sure how to get SEGM to give me the face here for replacement, since I don't want to paste a mask on each image as they are inferenced.

There are two methods available:
a) Directly perform the 'mask and' operation using "segm detector from person segm model" and "bbox detector from face model", or
b) Connect the two detectors (you can use SAM instead of person segm) into a SimpleDetector to obtain SEGS and then convert SEGS to a Combined Mask.

This is an example workflow of mask operation:
https://www.youtube.com/watch?v=5SCP9ijDuuA

**Comment by sedetweiler** [comment]
Geez.  I guess what I was doing was the easiest way.  Thank you for taking the time to help me with this.
