### ISSUE TITLE
the basic model check requires ComfyUI in path, this is not always valid

### ISSUE THREAD

**Issue by wyrde** [ltdrdata/ComfyUI-Impact-Pack#2]
My comfy installations don't have `ComfyUI` in the path. While this is safe to assume for those that use the standalone, it's not always true for manual or linux installs. The result is the models are downloaded and stored outside of comfy.

```
(venv) (base) PS D:\dev\sd.comfy> python .\main.py
Set vram state to: NORMAL_VRAM
Using xformers cross attention
Loading: ComfyUI-Impact-Pack
### ComfyUI-Impact-Pack: Check dependencies
WARNING: Ignoring invalid distribution -rotobuf (d:\dev\sd.py\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (d:\dev\sd.py\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (d:\dev\sd.py\venv\lib\site-packages)
### ComfyUI-Impact-Pack: Check basic models
Downloading https://cdn-lfs.huggingface.co/repos/cb/23/cb23b9f3fd8d6e9aee8c599e9e35770524a6a8efbf3add09ba96af3aada4d144/38208bb6b8a4633193feba532e96ed9a7942129af8fe948b27bfcf8e9a30a12e?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27mmdet_anime-face_yolov3.pth%3B+filename%3D%22mmdet_anime-face_yolov3.pth%22%3B&Expires=1681243449&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zL2NiLzIzL2NiMjNiOWYzZmQ4ZDZlOWFlZThjNTk5ZTllMzU3NzA1MjRhNmE4ZWZiZjNhZGQwOWJhOTZhZjNhYWRhNGQxNDQvMzgyMDhiYjZiOGE0NjMzMTkzZmViYTUzMmU5NmVkOWE3OTQyMTI5YWY4ZmU5NDhiMjdiZmNmOGU5YTMwYTEyZT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODEyNDM0NDl9fX1dfQ__&Signature=hDhyRVkJbH2BDrS502wttB5PU%7E71GyEccJjtJcDcMKasM0ig78LJpL5HZOrVQ8Yw3M97ozjgg6QGCJCJgIjjnjZTX57A9gC2LXnl7seZKzlcyycKEIfn85xDS21sRU4flEXoUE58ebN5uneUug2OYBdC1F-C9s2oV6dx7n7F0dGyaFPEFIyuacit-PRNeGKWGQ-2QCJ0j9cOCGK0%7EEPfWxlEoHYVSQvTPQ-r9PkgqQZXfJDKlxkW2e%7EoPdVjw7VnSaKp8RfAZPZh8Eh4yeEOtE6%7Es%7EuPA3-h--GbEwXZmZqlBRt2KHrrkcqVi1JCtwTIrFuZa77qXMgF31gBJxA-iw__&Key-Pair-Id=KVTP0A1DKRTAX to D:\dev\ComfyUI\models\mmdets\bbox\mmdet_anime-face_yolov3.pth
100%|██████████████████████████████████████████████████████████████| 246462357/246462357 [00:23<00:00, 10356830.11it/s]
Downloading https://raw.githubusercontent.com/Bing-su/dddetailer/master/config/mmdet_anime-face_yolov3.py to D:\dev\ComfyUI\models\mmdets\bbox\mmdet_anime-face_yolov3.py
100%|█████████████████████████████████████████████████████████████████████████| 5418/5418 [00:00<00:00, 5430045.18it/s]
Downloading https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth to D:\dev\ComfyUI\models\sams\sam_vit_b_01ec64.pth
100%|██████████████████████████████████████████████████████████████| 375042383/375042383 [00:16<00:00, 22838873.68it/s]
```

I changed comfyui-impact-pack.py

```
#if os.path.realpath("..").endswith("custom_nodes"):
#    # For user
#    comfy_path = os.path.realpath("../..")
#else:
#    # For development
#    comfy_path = os.path.realpath("../ComfyUI")
#-- hacked the above out. Probably better to search for "main.py", since main.py is in the root of comfy install.
comfy_path = os.path.realpath("./")
```

and it detects the models

**Comment by ltdrdata** [comment]
OMG, I completely forgot about that. The path needs to be taken from the ComfyUI module.

**Comment by ltdrdata** [comment]
I just fixed. check it.

**Comment by BARETFabrice** [comment]
I have another error, and my comfyUI repo is up to date.
I don't understand.

```
PS C:\Users\BARET\Desktop\App\ComfyUI\custom_nodes\ComfyUI-Impact-Pack> python .\comfyui-impact-pack.py
Loading: ComfyUI-Impact-Pack
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "C:\Users\BARET\Desktop\App\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\comfyui-impact-pack.py", line 58, in <module>
    import folder_paths
ModuleNotFoundError: No module named 'folder_paths'
PS C:\Users\BARET\Desktop\App\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>
```

**Comment by wyrde** [comment]
> I just fixed. check it.

woo hoo! \o/

**Comment by lord-lethris** [comment]
I am still getting this issue after updating to latest version:

```
File "\\?\E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\install.py", line 10, in <module>
    import folder_paths
ModuleNotFoundError: No module named 'folder_paths'
```

**Comment by ltdrdata** [comment]
> I am still getting this issue after updating to latest version:
> 
> ```
> File "\\?\E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\install.py", line 10, in <module>
>     import folder_paths
> ModuleNotFoundError: No module named 'folder_paths'
> ```

The issue occurred because you placed the custom_node directory somewhere other than under the ComfyUI directory.
I've patched it to work more robustly, so try updating it.
