### ISSUE TITLE
All my workflows with Preview Bridge are failing (unless the image on it already exists)

### ISSUE THREAD

**Issue by MockbaTheBorg** [ltdrdata/ComfyUI-Impact-Pack#224]
After installing the latest update, my workflows which have PreviewBridge on them won't load correctly.
The only way to make them work is to go to the 'temp' directory (or create it if not already there), put an image there, like 'empty.png', then blindly click on the image field of PreviewBridge and type 'empty.png' on it.
Then it works.

Steps to reproduce:
1 - Press "Clear" to have an empty workflow.
2 - Add a Preview Bridge to it, nothing else.
3 - Reload the page.

I get:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/8e14cc3b-7d47-449c-afc0-b37633519d6d)

Edit:  as a workaround I have changed '#placeholder' to 'empty.png' inside all my workflows and they now load correctly. Only problem is that I have to re-create 'empty.png' inside the temp folder every time I reload the server.

**Comment by ltdrdata** [comment]
This is fixed on aaad3860bd48421d66f4202ba6ccb6039c168d0b.

**Comment by MockbaTheBorg** [comment]
Awesome, thanks!

**Comment by MockbaTheBorg** [comment]
Upon testing I see a difference in behavior, but the issue seems to not be resolved.
Steps to reproduce:

1. Clear the workflow.
2. Add an Image Loader
3. Add a preview bridge
4. Add e preview image
5. Submit

The first submit yields nothing, the second submit shows an error:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/7fab1476-b679-4ca3-8c8c-4fe9444abe3c)

In the server log I get:
```
got prompt
ERROR:root:Failed to validate prompt for output 2:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: image
ERROR:root:* PreviewBridge 2:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 3:
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Required input is missing: image', 'extra_info': {}}
```
I hope this helps.

Thanks!

**Comment by ltdrdata** [comment]
> Author

Just fixed 973b555807a93df3a1c7b0da81b12aa8fa496a0c
It was conflict with pythongosssss's script.

**Comment by MockbaTheBorg** [comment]
Almost there ... now the first time the workflow is submitted the image shows, the second time (the input image is still the same), the preview bridge becomes empty.
Also, if an image is there, and the image's mask is edited, the image becomes blank.

Steps to reproduce (case 1):
1. clear workflow
2. add a load image
3. add a preview bridge
4. submit the workflow (preview gets populated)
5. submit again (preview gets cleared)

Steps to reproduce (case 2):
1. clear workflow
2. add a load image
3. add a preview bridge
4. submit the workflow (preview gets populated)
5. right click on the previewed image and open in mask editor
6. save to node (preview gets cleared)

Hope these steps help finding the issue.

(BTW ... I forgot to mention, I do use pythongossss and WAS)

**Comment by MockbaTheBorg** [comment]
After tha latest update and a few tests, everything seems to be working.
Thanks!

**Comment by ltdrdata** [comment]
> After tha latest update and a few tests, everything seems to be working.
> Thanks!

Actually. There is a bug. Just a HOTFIX.
I'll patch it more.

**Comment by ltdrdata** [comment]
Finally... fixed on df61f23875ca7463c720d059e466385ac3a5041e

In the previous version, there was a phenomenon where `PreviewBridge` would always run one more time when the input image changed.

**Comment by MockbaTheBorg** [comment]
This commit actually created a problem. 
Now when you draw a mask onto the contents of the preview bridge, it updates into the image but it is not sent.
I have tried to write my own PB, so I believe you got into the same issue I got, though I have no idea how to deal with node IDs.
When you save the modified image with the mask back onto the node, it becomes a new filename. You might be continuing to get the mask information from the original (named after the ID) image, therefore mask stays 64x64 black.

Steps to reproduce:
1. Clear workflow
2. Add image load with an image
3. Add PB, mask to image and preview image
4. Submit workflow (mask is black 64x64)
5. Edit PB mask and save
6. Submit workflow (mask continues 64x64)

My idea of a solution (in my case) was to mix SaveImage with LoadImage. For that I compute a sha256 of the image pixels entering the PB and of the image pixels currently in the PB. This way I would only save a new image if a different one was entering.
If the pixels are the same, continue using the image currently in PB (mask edited or not).
If the pixels are different, replace the saved, and continue.
I got the same problem as above though, as I was not accounting for the change in filename (I have no idea how to fix that).
My plan was for the PB image name for comparing the pixels to be named based on the node id, and I would always compare to this one, however keep working on the one modified by changing the mas, if any change was done.

**Comment by MockbaTheBorg** [comment]
This is the rig I use to test.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/6624ad71-1260-4689-a798-6787430e32a4)

I use preview bridge a lot on my workflows to receive the first image from a previous workflow and then keep modifying the mask to add details, or to make sure that the image I save to the next workflow indeed matches what I see.
Instead of making a huge workflow which "does everything", I open multiple ones on different browser tabs, and switch among them as needed ... [initial]->[img2img]->[inpaint]->[upscale].
The image generated in the initial is carried over saved on a file, and PB is there to help me keep track of the changes.

**Comment by MockbaTheBorg** [comment]
Your previous one, 776d75f, was working fine like this:

Observe the filename before the mask gets edited:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/c723281c-1979-42a5-b331-836c90158c55)

And after the mask gets edited:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/7227410d-eac8-4168-9b3b-91e28216e4ad)

Observe also that, even though I have generated a new default.png on another tab of the browser it doesn't get updated on the image loader .. that's exactly where PB comes to the rescue.

**Comment by ltdrdata** [comment]
> This commit actually created a problem. Now when you draw a mask onto the contents of the preview bridge, it updates into the image but it is not sent. I have tried to write my own PB, so I believe you got into the same issue I got, though I have no idea how to deal with node IDs. When you save the modified image with the mask back onto the node, it becomes a new filename. You might be continuing to get the mask information from the original (named after the ID) image, therefore mask stays 64x64 black.
> 
> Steps to reproduce:
> 
> 1. Clear workflow
> 2. Add image load with an image
> 3. Add PB, mask to image and preview image
> 4. Submit workflow (mask is black 64x64)
> 5. Edit PB mask and save
> 6. Submit workflow (mask continues 64x64)
> 
> My idea of a solution (in my case) was to mix SaveImage with LoadImage. For that I compute a sha256 of the image pixels entering the PB and of the image pixels currently in the PB. This way I would only save a new image if a different one was entering. If the pixels are the same, continue using the image currently in PB (mask edited or not). If the pixels are different, replace the saved, and continue. I got the same problem as above though, as I was not accounting for the change in filename (I have no idea how to fix that). My plan was for the PB image name for comparing the pixels to be named based on the node id, and I would always compare to this one, however keep working on the one modified by changing the mas, if any change was done.


This issue should be fixed on df61f23875ca7463c720d059e466385ac3a5041e
Is it `### Loading: ComfyUI-Impact-Pack (V4.23.6)`?

**Comment by MockbaTheBorg** [comment]
> > This commit actually created a problem. Now when you draw a mask onto the contents of the preview bridge, it updates into the image but it is not sent. I have tried to write my own PB, so I believe you got into the same issue I got, though I have no idea how to deal with node IDs. When you save the modified image with the mask back onto the node, it becomes a new filename. You might be continuing to get the mask information from the original (named after the ID) image, therefore mask stays 64x64 black.
> > Steps to reproduce:
> > 
> > 1. Clear workflow
> > 2. Add image load with an image
> > 3. Add PB, mask to image and preview image
> > 4. Submit workflow (mask is black 64x64)
> > 5. Edit PB mask and save
> > 6. Submit workflow (mask continues 64x64)
> > 
> > My idea of a solution (in my case) was to mix SaveImage with LoadImage. For that I compute a sha256 of the image pixels entering the PB and of the image pixels currently in the PB. This way I would only save a new image if a different one was entering. If the pixels are the same, continue using the image currently in PB (mask edited or not). If the pixels are different, replace the saved, and continue. I got the same problem as above though, as I was not accounting for the change in filename (I have no idea how to fix that). My plan was for the PB image name for comparing the pixels to be named based on the node id, and I would always compare to this one, however keep working on the one modified by changing the mas, if any change was done.
> 
> This issue should be fixed on [df61f23](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/df61f23875ca7463c720d059e466385ac3a5041e) Is it `### Loading: ComfyUI-Impact-Pack (V4.23.6)`?

yes
df61f23 - 4.23.6

**Comment by ltdrdata** [comment]
> > > This commit actually created a problem. Now when you draw a mask onto the contents of the preview bridge, it updates into the image but it is not sent. I have tried to write my own PB, so I believe you got into the same issue I got, though I have no idea how to deal with node IDs. When you save the modified image with the mask back onto the node, it becomes a new filename. You might be continuing to get the mask information from the original (named after the ID) image, therefore mask stays 64x64 black.
> > > Steps to reproduce:
> > > 
> > > 1. Clear workflow
> > > 2. Add image load with an image
> > > 3. Add PB, mask to image and preview image
> > > 4. Submit workflow (mask is black 64x64)
> > > 5. Edit PB mask and save
> > > 6. Submit workflow (mask continues 64x64)
> > > 
> > > My idea of a solution (in my case) was to mix SaveImage with LoadImage. For that I compute a sha256 of the image pixels entering the PB and of the image pixels currently in the PB. This way I would only save a new image if a different one was entering. If the pixels are the same, continue using the image currently in PB (mask edited or not). If the pixels are different, replace the saved, and continue. I got the same problem as above though, as I was not accounting for the change in filename (I have no idea how to fix that). My plan was for the PB image name for comparing the pixels to be named based on the node id, and I would always compare to this one, however keep working on the one modified by changing the mas, if any change was done.
> > 
> > 
> > This issue should be fixed on [df61f23](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/df61f23875ca7463c720d059e466385ac3a5041e) Is it `### Loading: ComfyUI-Impact-Pack (V4.23.6)`?
> 
> yes [df61f23](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/df61f23875ca7463c720d059e466385ac3a5041e) - 4.23.6

Can you share full list of your custom-nodes?

**Comment by MockbaTheBorg** [comment]
ComfyUI-Manager
ComfyUI-ImpackPack
Comfyui Controlnet Auxiliary Processors
ClipSeg
WAS Node Suite
PythonGosssss Custom Scripts
Reactor
ComfyUI stable wildcards


![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/2b593dea-f60c-4e58-bc07-6710a5f42217)

**Comment by ltdrdata** [comment]
Just fixed bdc64ce6e529477c3b1e061d5935a5bd96ea5c62.

I confirmed that it works without any issues in the same configuration as yours. In fact, it's almost miraculous how it worked perfectly before the patch.

**Comment by MockbaTheBorg** [comment]
All my workflows have worked, but one.
My "Inpaint" workflow crashes on PB if the "temp" folder is not there or empty.
You can reproduce if you do:

1. Empty workflow
2. Add image load with an image on it
3. Add PB
4. Submit the workflow
5. Go to the "temp" folder and delete the image created by PB inside the PreviewBridge folder (to simulated a just-started server)
6. Reload the page, the PB becomes all gray.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/16762507/3a902988-f8f8-4ec8-84e5-d57bd9de6a2d)

This is what is happening when I load my Inpaint workflow.
I am attaching both the workflow and the custom-nodes file with some nodes I made (needed to load "Inpaint").

[Tmp.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12918980/Tmp.zip)

Hope this helps. 
My expected behavior was: if temp is not there or gets deleted by whatever reason, PB still loads normally and gets populated on the first submission.

**Comment by ltdrdata** [comment]
Is there reason why you remove temp dir during ComfyUI is running? 

Many ComfyUI nodes relies on temp directory. 

The "temp" directory must be ensured not to be deleted while ComfyUI is running.

**Comment by MockbaTheBorg** [comment]
Not in regular operation, I did just so I could re-create and illustrate the issue.
When I (re-)start my server though, all the folders are cleared. Input/Output are emptied so I can start fresh with a new project.
For some reason, loading the "Inpaint" workflow was failing. If "Temp" was not there.
Now, somehow, after applyting the latest ComfyUI-Manager update, the problem is not happening anymore. I have no idea why.
Everything seems to be working correctly now.
(I will report back with a new issue in case anything strange happens, hopefully not)

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/227

It seems firefox has problem.

**Comment by ltdrdata** [comment]
I just fixed this.
But, I found a ComfyUI bug related to firefox.

https://github.com/comfyanonymous/ComfyUI/pull/1797

It worked correctly when this patch was applied.
